-- ALTER TABLE DIRECT.C_PRD_MST ADD PRD_MST_RDP_P_CMS_CD VARCHAR2(4) DEFAULT '';
-- ALTER TABLE DIRECT.C_PRD_MST ADD PRD_MST_RDP_P_CMS NUMBER DEFULAT 0,
-- ALTER TABLE DIRECT.C_PRD_MST ADD PRD_MST_RDP_P_DVD_PAY NUMBER DEFAULT 0,
-- ALTER TABLE DIRECT.C_PRD_MST ADD PRD_MST_RDP_P_DVD_CNT NUMBER DEFAULT 1,
-- COMMENT ON COLUMN DIRECT.C_PRD_MST.PRD_MST_RDP_P_CMS_CD IS '개인레디플래너수수료 코드';
-- COMMENT ON COLUMN DIRECT.C_PRD_MST.PRD_MST_RDP_P_CMS IS '개인레디플래너총수수료';
-- COMMENT ON COLUMN DIRECT.C_PRD_MST.PRD_MST_RDP_P_DVD_PAY IS '개인레디플레너분할금액';
-- COMMENT ON COLUMN DIRECT.C_PRD_MST.PRD_MST_RDP_P_DVD_CNT IS '개인레디플레너분할회차';



-- "PRC_PAY_CLS" NUMBER NOT NULL,
-- "PRC_RDP_CMS_CD" VARCHAR2(4),
-- "PRC_RDP_CMS" NUMBER,
-- "PRC_RDP_DVD_PAY" NUMBER,
-- "PRC_RDP_DVD_CNT" NUMBER,
--
-- ------------------- 오리진 ------------
-- PRD_MST_RDP_CMS_CD, --DEPRECATE
-- PRD_MST_RDP_CMS, --DEPRECATE
-- PRD_MST_RDP_DVD_PAY, --DEPRECATE
-- PRD_MST_RDP_DVD_CNT, --DEPRECATE
--
-- ------------------- 새컬럼 ------------
-- CPMRC.PRC_RDP_CMS_CD,
-- CPMRC.PRC_RDP_CMS,
-- CPMRC.PRC_RDP_DVD_PAY,
-- CPMRC.PRC_RDP_DVD_CNT,
-- ------------------- 개인수수료컬럼 ------------
-- CPMRC1.PRC_RDP_CMS_CD AS PRC_RDP_P_CMS_CD,
-- CPMRC1.PRC_RDP_CMS AS PRC_RDP_P_CMS,
-- CPMRC1.PRC_RDP_DVD_PAY AS PRC_RDP_P_DVD_PAY,
-- CPMRC1.PRC_RDP_DVD_CNT AS PRC_RDP_P_DVD_CNT,




--DROP TABLE C_PRD_MST_RDP_CMS;
CREATE  TABLE "DIRECT"."C_PRD_MST_RDP_CMS"
(
    "PRD_MST_NO" VARCHAR2(20) NOT NULL ENABLE,
    "PRC_PAY_CLS" NUMBER NOT NULL,
    "PRC_RDP_CMS_CD" VARCHAR2(4),
    "PRC_RDP_CMS" NUMBER,
    "PRC_RDP_DVD_PAY" NUMBER,
    "PRC_RDP_DVD_CNT" NUMBER,
    "PRC_UPD_DT" CHAR(14),
    "PRC_UPD_IP" VARCHAR2(20) NOT NULL ENABLE,
    "PRC_UPD_ID" VARCHAR2(20) NOT NULL ENABLE,
    CONSTRAINT "C_PRD_MST_RDP_CMS_PK" PRIMARY KEY ("PRD_MST_NO", "PRC_PAY_CLS")
) ;

COMMENT ON COLUMN DIRECT.C_PRD_MST_RDP_CMS.PRD_MST_NO IS '결합상품코드';
COMMENT ON COLUMN DIRECT.C_PRD_MST_RDP_CMS.PRC_PAY_CLS IS '사업자유형';
COMMENT ON COLUMN DIRECT.C_PRD_MST_RDP_CMS.PRC_RDP_CMS_CD IS '개인레디플래너수수료 코드';
COMMENT ON COLUMN DIRECT.C_PRD_MST_RDP_CMS.PRC_RDP_CMS IS '레디플래너총수수료';
COMMENT ON COLUMN DIRECT.C_PRD_MST_RDP_CMS.PRC_RDP_DVD_PAY IS '레디플레너분할금액';
COMMENT ON COLUMN DIRECT.C_PRD_MST_RDP_CMS.PRC_RDP_DVD_CNT IS '레디플레너분할회차';
COMMENT ON COLUMN DIRECT.C_PRD_MST_RDP_CMS.PRC_UPD_DT IS '최종_수정일';
COMMENT ON COLUMN DIRECT.C_PRD_MST_RDP_CMS.PRC_UPD_IP IS '최종_수정_IP';
COMMENT ON COLUMN DIRECT.C_PRD_MST_RDP_CMS.PRC_UPD_ID IS '최종_수정자_아이디';
COMMIT ;

