-- ALTER TABLE DIRECT.T_PRD_MST ADD PRD_MST_REC_TXT_YN CHAR(1) DEFAULT 'N';

ALTER TABLE DIRECT.C_PRD_MST ADD PRD_MST_REC_TXT_YN CHAR(1) DEFAULT 'N';
ALTER TABLE DIRECT.T_ORD_MST ADD ORD_MST_REC_TXT VARCHAR2(40) DEFAULT '';
